name: nomad_taxi
#TODO(tima): write description
description: "Nomad Taxi"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


# * Flutter Packages overrides for conflict resolution
dependency_overrides:
  intl: ^0.18.1
  file: ^7.0.0


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # * Project Utilities
  # Localization
  flutter_localizations:
    sdk: flutter
  # Localization package
  intl: ^0.18.0
  intl_utils: ^2.8.1
  # Flavoring
  flutter_flavorizr: ^2.1.5
  # Icon Generator
  flutter_launcher_icons: ^0.13.0
  # Native Splash Screen
  flutter_native_splash: ^2.2.15
  # Multiple Search Selection
  search_choices: ^2.2.5


  # * Navigation and routing
  # Main Application Router
  go_router: ^10.2.0
  # URL Launcher
  url_launcher: ^6.1.8


  # * Functional programming
  # Either
  fpdart: ^1.1.0

  # * Network and API
  # Http client
  dio: ^5.2.1+1

  # * Development Utilities
  # Logging
  l: ^4.0.0
  stack_trace: ^1.11.0
  # Crash Reporting
  sentry_flutter: ^7.10.1
  # Helpers
  pure: 0.2.0
  collection: ^1.17.1

  # * Data Management
  path_provider: ^2.0.0
  path: ^1.8.2


  # * State Management
  # BLoC pattern
  flutter_bloc: ^8.1.1
  # Package that exposes custom event transformers
  bloc_concurrency: ^0.2.2
  # Reactive Programming
  rxdart: ^0.27.7

  # * Dependency Injection
  # Dependency Injection
  injectable: <2.1.2
  # Service Locator
  get_it: ">=7.2.0 <7.3.0"

  # * File and Path Management
  # File Picker
  file_picker: ^5.2.5
  # Image Manipulation
  image: ^4.0.17

  # * General Utilities
  # Object Comparison
  equatable: ^2.0.5
  # UUID Generator
  uuid: ^3.0.4
  # Internet Connection Checker
  internet_connection_checker: ^1.0.0+1
  # Connectivity Checker
  connectivity_plus: ^5.0.2
  # Check Internet connection
  check_vpn_connection: ^0.0.2
  # Ping to server
  dart_ping: ^9.0.1
  # Svg Images
  flutter_svg: ^2.0.5
  pull_to_refresh: ^2.0.0
  # Isolate manager
  worker_manager: ^6.1.1
  # Asynchronous computations
  async: ^2.11.0
  # Scroll Controller Group
  sync_scroll_controller: ^1.0.1
  # Flutter Icon Generator
  icons_launcher: ^2.1.7
  # Shimmer loading effect
  shimmer: ^3.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  # * Code Generators
  # Generating Files
  build_runner: ^2.4.6
  # Generating Serialization of JSON
  json_serializable: ^6.7.0
  # Code Generation for Models and Union Types
  freezed: ^2.3.5
  # Generating Asset Files
  flutter_gen_runner: ^5.3.0
  # Injecting Dependencies
  injectable_generator: ^2.1.6
  # Generate Drift Files
  drift_dev: ^2.11.2
  # FFI gen
  ffigen: ^9.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/icons/brand/
    - assets/icons/check_out/
    - assets/icons/location/
    - assets/icons/point/
    - assets/icons/regular/
    - assets/icons/solid/
    - assets/icons/toggle/
    - assets/images/
    - assets/splash/

  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


ffigen:
  output: "generated_bindings.dart"
  headers:
    entry-points:
      - "example.h"

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true


# * Flutter Icon Generator Configurations

icons_launcher:
  image_path: 'assets/icons/prod.png'
  platforms:
    android:
      enable: true
      image_path: 'assets/icons/prod.png'
      adaptive_foreground_image: 'assets/icons/prod.png'
      adaptive_background_color: '#ff004d'
      
      # adaptive_background_image: 'assets/ic_background.png'
      # adaptive_round_image: 'assets/ic_logo_round.png'
      # adaptive_monochrome_image: 'assets/ic_logo_monochrome.png'
    ios:
      enable: true
      image_path: 'assets/icons/prod.png'


# * Flutter Splash Screen Generator Configurations

flutter_native_splash:
  android: true
  ios: true
  color: "FF004D" 
  color_dark: "FF004D"
  image: assets/splash/splash.png
  image_dark: assets/splash/splash.png
  fullscreen: true
  android_12:
    image: assets/splash/splash.png
    image_dark: assets/splash/splash.png
    icon_background_color: "#FF004D"
    icon_background_color_dark: "#FF004D"

# Localizations generating config
flutter_intl:
  enabled: true
  class_name: S
  main_locale: ru
  arb_dir: lib/src/core/localization/l10n
  output_dir: lib/src/core/localization/generated
  untranslated_messages_file: lib/src/core/localization/l10n/untranslated_messages.txt
