name: nomad_taxi
#TODO(tima): write description
description: "Nomad Taxi"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


# * Flutter Packages overrides for conflict resolution
# dependency_overrides:
#   intl: ^0.18.1
#   file: ^7.0.0


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # * Project Utilities
  # Localization
  flutter_localizations:
    sdk: flutter
  # Localization package
  intl: ^0.19.0
  intl_utils: ^2.8.7
  # Flavoring
  flutter_flavorizr: ^2.2.3
  # Icon Generator
  flutter_launcher_icons: ^0.13.1
  # Native Splash Screen
  flutter_native_splash: ^2.4.0
  # Multiple Search Selection
  search_choices: ^2.2.7
  flutter_widget_from_html: ^0.15.0

  file: ^7.0.0


  # * Navigation and routing
  # Main Application Router
  go_router: ^14.1.2
  # URL Launcher
  url_launcher: ^6.2.6


  # * Functional programming
  # Either
  fpdart: ^1.1.0

  # * Network and API
  # Http client
  dio: ^5.4.3+1
  # Internet Connection Checker
  internet_connection_checker: ^1.0.0+1
  # Connectivity Checker
  connectivity_plus: ^6.0.3
  # Check Internet connection
  check_vpn_connection: ^0.0.2
  # Ping to server
  dart_ping: ^9.0.1
  # Map
  geolocator: ^12.0.0
  maplibre_gl_workspace:
      git:
        url: https://github.com/maplibre/flutter-maplibre-gl.git
        ref: main

  # * Development Utilities
  # Logging
  l: ^4.0.2
  stack_trace: ^1.11.1
  # Crash Reporting
  sentry: ^8.2.0
  sentry_flutter: ^8.2.0
  # * Data Management
  path_provider: ^2.1.3
  path: ^1.9.0

  # * State Management
  # BLoC pattern
  flutter_bloc: ^8.1.5
  # Package that exposes custom event transformers
  bloc_concurrency: ^0.2.5
  # Reactive Programming
  rxdart: ^0.27.7

  # * Dependency Injection
  # Dependency Injection
  injectable: ^2.4.2
  # Service Locator
  get_it: ^7.7.0

  # * File and Path Management
  # File Picker
  file_picker: ^8.0.3
  # Image Manipulation
  image: ^4.1.7

  # * General Utilities
  # Object Comparison
  equatable: ^2.0.5
  # UUID Generator
  uuid: ^4.4.0

  
  # Svg Images
  flutter_svg: ^2.0.10+1
  # pull_to_refresh: ^2.0.0
  # Isolate manager
  worker_manager: ^7.0.2
  # Asynchronous computations
  async: ^2.11.0
  # Scroll Controller Group
  sync_scroll_controller: ^1.0.1
  # Flutter Icon Generator
  icons_launcher: ^2.1.7
  # Shimmer loading effect
  shimmer: ^3.0.0
  gap: ^3.0.1
  hive_flutter: ^1.1.0
  freezed: ^2.5.2
  custom_refresh_indicator: ^3.1.0
  json_annotation: ^4.9.0
  maplibre_gl: ^0.20.0


  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  # * Code Generators
  # Generating Files
  build_runner: ^2.4.10
  # Generating Serialization of JSON
  json_serializable: ^6.8.0
  # Code Generation for Models and Union Types
  freezed_annotation: ^2.4.1
  # Generating Asset Files
  flutter_gen_runner: ^5.5.0+1
  # Injecting Dependencies
  injectable_generator: ^2.6.1
  # FFI gen
  ffigen: ^12.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/icons/brand/
    - assets/icons/check_out/
    - assets/icons/location/
    - assets/icons/point/
    - assets/icons/regular/
    - assets/icons/solid/
    - assets/icons/toggle/
    - assets/splash/
    - assets/fonts/
    - assets/images/

  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100


ffigen:
  output: "generated_bindings.dart"
  headers:
    entry-points:
      - "example.h"

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true


# * Flutter Icon Generator Configurations

icons_launcher:
  image_path: 'assets/icons/prod.png'
  platforms:
    android:
      enable: true
      image_path: 'assets/icons/prod.png'
      adaptive_foreground_image: 'assets/icons/prod.png'
      adaptive_background_color: '#ff004d'
      
      # adaptive_background_image: 'assets/ic_background.png'
      # adaptive_round_image: 'assets/ic_logo_round.png'
      # adaptive_monochrome_image: 'assets/ic_logo_monochrome.png'
    ios:
      enable: true
      image_path: 'assets/icons/prod.png'


# * Flutter Splash Screen Generator Configurations

flutter_native_splash:
  android: true
  ios: true
  color: "FF004D" 
  color_dark: "FF004D"
  image: assets/splash/splash.png
  image_dark: assets/splash/splash.png
  fullscreen: true
  android_12:
    image: assets/splash/splash.png
    image_dark: assets/splash/splash.png
    icon_background_color: "#FF004D"
    icon_background_color_dark: "#FF004D"

# Localizations generating config
flutter_intl:
  enabled: true
  class_name: S
  main_locale: ru
  arb_dir: lib/src/core/localization/l10n
  output_dir: lib/src/core/localization/generated
  untranslated_messages_file: lib/src/core/localization/l10n/untranslated_messages.txt
